daria_hand_to_heni_portrait:
        width: 1024
        height: 576
        labels: 0
        data:
                - source: ~/media/Daria_hand.MP4
                  options:
                          - train-a
                - source: ~/media/Portrait-C0025_1.mp4
                  options:
                          - trim 0:94.1
                          - train-b
        train:
                global:
                        epochs: 14
                local:
                        epochs: 24
        generate:
                options:
                        - codec prores
heni_portrait:
        width: 1024
        height: 576
        data:
                - source: ~/media/PORTRAIT_C0021.mov
                  options:
                          - exclude-landmark jaw
                - source: ~/media/daria_headshot.mp4
                  name: daria_headshot
                  options:
                          - exclude-landmark jaw
                          - directory-prefix test
                          - flip vh
        train:
                global:
                        epochs: 14
                local:
                        epochs: 20
        generate:
                data: daria_headshot
                options:
                        - codec prores
                        - fps 30.03
mt_daria2_heni3:
        width: 1024
        height: 576
        labels: 26
        data:
                - source: ~/media/source_daria_2_trimmed.mov
                  options:
                          - label-with openpose
                          - no-label-face
                          - directory-prefix test
                - source: ~/media/target_heni_3.MP4
                  options:
                          - label-with openpose
                          - no-label-face
        normalize:
                options:
                        - zthreshold 0.5
        train:
                global:
                        epochs: 12
                        options:
                                - no_flip
                local: 
                        epochs: 40
                        options:
                                - no_flip
        generate:
                options:
                        - codec prores

mt_daria2_heni3_sq:
        width: 1024
        height: 1024
        labels: 26
        data:
                - source: ~/media/source_daria_2_trimmed.mov
                  resize: false
                  crop: true
                  options:
                          - label-with openpose
                          - no-label-face
                          - directory-prefix test
                - source: ~/media/target_heni_3.MP4
                  resize: false
                  crop: true
                  options:
                          - label-with openpose
                          - no-label-face
        normalize: true
        train:
                global:
                        epochs: 6
                        options:
                                - no_flip
                local: 
                        epochs: 20
                        options:
                                - no_flip
        generate:
                options:
                        - codec prores
mt_daria2_heni3_sq_lores:
        width: 512
        height: 512
        labels: 26
        data:
                - source: ~/media/source_daria_2_trimmed.mov
                  resize: 1024x576
                  crop: true
                  options:
                          - label-with openpose
                          - no-label-face
                          - directory-prefix test
                - source: ~/media/target_heni_3.MP4
                  resize: 1024x576
                  crop: true
                  options:
                          - label-with openpose
                          - no-label-face
        normalize: true
        train:
                global:
                        epochs: 12
                        options:
                                - no_flip
                local: 
                        epochs: 40
                        ngf: 32
                        options:
                                - no_flip
        generate:
                options:
                        - codec prores

